name: OSV-Scanner Nightly Scan
on:
  schedule:
    - cron: '0 2 * * *'  # 2 AM UTC daily
  workflow_dispatch:      # Optional manual trigger

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Required for pushing changes

      - name: Install OSV-Scanner
        run: |
          curl -L https://github.com/google/osv-scanner/releases/latest/download/osv-scanner_linux_amd64 -o osv-scanner
          chmod +x osv-scanner
          sudo mv osv-scanner /usr/local/bin/

      - name: Run scan (ignore errors)
        run: |
          osv-scanner scan source --r --format html . > output.html || true

      - name: Commit and push report
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add output.html
          git commit -m "[Automated] Update OSV scan report" || echo "No changes to commit"
          git push